[project]
name = "palgen"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "loguru>=0.7.3",
    "pydantic>=2.11.7",
    "sqlalchemy>=2.0.41",
]
[project.scripts]
palgen = "palgen.cli:main"
